name: Serving Our Neighbors
favicon: null
layout_spectrum: 0.27292210748419166
typography_spectrum: 0.14608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23996675200760365
  lightness: 0.7050084765069187
  saturation: 0.2490366257261485
  rhythmicContrast: 0.08654304570518434
purpose: []
